---
dist: trusty
language: elixir
elixir:
  - 1.6.4
otp_release:
  - 20.3.2
cache:
  directories:
    - _build
    - deps
script:
  - mix format --check-formatted
  - MIX_ENV=test mix do compile --warnings-as-errors, coveralls.json
after_success:
  - bash <(curl -s https://codecov.io/bash)
